=== sneakyPad/semantic-technologies/Aufgabe1a/validation.dtd
<!ELEMENT movieDb (conductors,movies,actors)>

<!ELEMENT conductors (conductor)+>
<!ELEMENT conductor (name)>
<!ELEMENT name (lastname,firstname)>
<!ATTLIST conductor
    id ID #REQUIRED 
    conducted CDATA #REQUIRED 
>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>


<!ELEMENT movies (movie)+>
<!ELEMENT movie (title, year)>
<!ATTLIST movie
    id ID #REQUIRED 
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT actors (actor)+>
<!ELEMENT actor (name)>
<!ATTLIST actor
    id ID #REQUIRED 
    playedIn CDATA #REQUIRED
>

=== sneakyPad/semantic-technologies/Aufgabe1a/movieDb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movieDb SYSTEM "./validation.dtd">
<movieDb>
    <conductors>
        
        <conductor id="pwegener" conducted="studprag,golem">
            <name>
                <lastname>Wegener</lastname>
                <firstname>Paul</firstname>
            </name>
        </conductor>
        <conductor id="fwmurnau" conducted="satanas,dlmann">
            <name>
                <lastname>Murnau</lastname>
                <firstname>F.W.</firstname>
            </name>
        </conductor>
        <conductor id="flang" conducted="drmabuse,nibelungen,metropolis,spione,fimmond">
            <name>
                <lastname>Lang</lastname>
                <firstname>Fritz</firstname>
            </name>
        </conductor>
        <conductor id="rschuenzel" conducted="saisonkairo,amphytrion">
            <name>
                <lastname>Schünzel</lastname>
                <firstname>Reinhold</firstname>
            </name>
        </conductor>
        <conductor id="khartl" conducted="fp1,sholmes">
            <name>
                <lastname>Hartl</lastname>
                <firstname>Karl</firstname>
            </name>
        </conductor>
    </conductors>
    <movies>
        <movie id="studprag">
            <title>Der Student von Prag</title>
            <year>1913</year>
        </movie>
        <movie id="golem">
            <title>Der Golem</title>
            <year>1914</year>
        </movie>
        <movie id="satanas">
            <title>Satanas</title>
            <year>1919</year>
        </movie>
        <movie id="drmabuse">
            <title>Dr. Mabuse, der Spieler</title>
            <year>1921</year>
        </movie>
        <movie id="nibelungen">
            <title>Die Nibelungen, 1. Teil: Siegfried</title>
            <year>1922</year>
        </movie>
        <movie id="dlmann">
            <title>Der letzte Mann</title>
            <year>1924</year>
        </movie>
        <movie id="metropolis">
            <title>Metropolis</title>
            <year>1925</year>
        </movie>
        <movie id="spione">
            <title>Spione</title>
            <year>1927</year>
        </movie>
        <movie id="fimmond">
            <title>Frau im Mond</title>
            <year>1928</year>
        </movie>
        <movie id="fp1">
            <title>F.P.1 antwortet nicht</title>
            <year>1932</year>
        </movie>
        <movie id="saisokairo">
            <title>Saison in Kairo</title>
            <year>1933</year>
        </movie>
        <movie id="amphytrion">
            <title>Amphytrion</title>
            <year>1935</year>
        </movie>
        <movie id="sholmes">
            <title>Der Mann, der Sherlock Holmes war</title>
            <year>1937</year>
        </movie>
    </movies>
    <actors>
        <actor id="bgoetzke" playedIn="jagtode,drmabuse,nibelungen">
            <name>
                <lastname>Goetzke</lastname>
                <firstname>Bernhard</firstname>
            </name>
        </actor>
        <actor id="rkleinrogge" playedIn="drmabuse,metropolis,spione">
            <name>
                <lastname>Klein-Rogge</lastname>
                <firstname>Rudolf</firstname>
            </name>
        </actor>
        <actor id="aabel" playedIn="drmabuse,metropolis,dubarry">
            <name>
                <lastname>Abel</lastname>
                <firstname>Alfred</firstname>
            </name>
        </actor>
        <actor id="gjohn" playedIn="drmabuse,nibelungen,dlmann,fp1">
            <name>
                <lastname>John</lastname>
                <firstname>Georg</firstname>
            </name>
        </actor>
        <actor id="tloos" playedIn="homunculus,nibelungen,metropolis,lb17">
            <name>
                <lastname>Loos</lastname>
                <firstname>Theodor</firstname>
            </name>
        </actor>
        <actor id="frasp" playedIn="metropolis,spione,fimmond,emil">
            <name>
                <lastname>Rasp</lastname>
                <firstname>Fritz</firstname>
            </name>
        </actor>
        <actor id="kplaten" playedIn="dubarry,fimmond,bettelstud">
            <name>
                <lastname>Platen</lastname>
                <firstname>Karl</firstname>
            </name>
        </actor>
        <actor id="wfritsch" playedIn="spione,fimmond,tankstelle,saisonkairo,amphytrion,fdiplomaten">
            <name>
                <lastname>Fritsch</lastname>
                <firstname>Willy</firstname>
            </name>
        </actor>
        <actor id="halbers" playedIn="dubarry,blengel,fp1,sholmes,muenchhausen">
            <name>
                <lastname>Albers</lastname>
                <firstname>Hans</firstname>
            </name>
        </actor>
        <actor id="hruehmann" playedIn="tankstelle,sholmes,klmleute,quax,feuerzangen">
            <name>
                <lastname>Rühmann</lastname>
                <firstname>Heinz</firstname>
            </name>
        </actor>
        <actor id="awaescher" playedIn="amphytrion,fdiplomaten,klmleute">
            <name>
                <lastname>Wäscher</lastname>
                <firstname>Aribert</firstname>
            </name>
        </actor>
        <actor id="bhelm" playedIn="metropolis">
            <name>
                <lastname>Helm</lastname>
                <firstname>Brigitte</firstname>
            </name>
        </actor>
        <actor id="mdietrich" playedIn="dubarry,blengel">
            <name>
                <lastname>Dietrich</lastname>
                <firstname>Marlene</firstname>
            </name>
        </actor>
    </actors>
</movieDb>
